---
kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    username: sonph1995
    password: sonph1995
    repo: sonph1995/busytest
    dockerfile: Dockerfile
...